[options]
HoldPkg     = pacman glibc
Architecture = auto

Color
ILoveCandy
VerbosePkgLists
ParallelDownloads = 10
#CheckSpace
DownloadUser = alpm

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# Faster downloads (forces IPv4 if ISP IPv6 routing is bad)
#XferCommand = /usr/bin/curl -L -C - --retry 5 --retry-delay 3 -f -o %o %u

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[multilib]
#Include = /etc/pacman.d/mirrorlist

[ri]
SigLevel = Optional TrustAll
Server = https://himadrichakra12.github.io/ri/$arch
