return {
    universal = {
        new_tab         = "<Ctrl>t",
        close_tab       = "<Ctrl>w",
        new_win         = "<Ctrl>n",
        next_tab        = "<Ctrl>Tab",
        prev_tab        = "<Ctrl><Shift>Tab",
        go_back         = "<",
        go_forward      = ">",
        go_parent       = "BackSpace",
        go_home         = "<Shift>H",
        rename          = "F2",
        copy            = "<Ctrl>c",
        cut             = "<Ctrl>x",
        paste           = "<Ctrl>v",
        delete          = "Delete",
        trash           = "<Shift>Delete",
        new_folder      = "<Ctrl><Shift>n",
        select_all      = "<Ctrl>a",
        invert_sel      = "<Ctrl>i",
        toggle_hidden   = "<Ctrl>h",
        reload          = "<Ctrl>r",
        focus_path      = "/",
        extract_here    = "<Ctrl><Shift>e",
        compress        = "<Ctrl><Shift>c",
    },
    list = {
        move_down       = "j",
        move_up         = "k",
        move_top        = "g",          -- gg handled in view handler
        move_bottom     = "G",
        page_down       = "<Ctrl>d",
        page_up         = "<Ctrl>u",
        open            = "Return",
        open_new_tab    = "t",
        expand_dir      = "l",          -- expand tree node (list-tree mode)
        collapse_dir    = "h",
    },
    icon = {
        move_down       = "j",
        move_up         = "k",
        move_left       = "h",
        move_right      = "l",
        page_down       = "<Ctrl>d",
        page_up         = "<Ctrl>u",
        open            = "Return",
        open_new_tab    = "t",
    },
}
